### ISSUE TITLE
Demo script error

### ISSUE THREAD

**Issue by noblec04** [al1brn/geonodes#1]
Heya

In your demo script, I get an error saying mesh doesn't have "position" using grid.position.

it works smoothly if I use grid.point.position instead.

I'm working in 3.2 alpha at the moment.

This module is awesome!! thank you for making it!

**Comment by al1brn** [comment]
Thank you for the feedback. I have to update the demo scripts. I recently changed how fields are implemented. The doc is not up to date. 

Now the fields are called via "domains" : mesh.point.position rather than mesh.position. I find it clearer and more "natural"

Globally this is an alpha version not that stable. 

Br

**Comment by noblec04** [comment]
Ah, more than fair!

Sorry for jumping the gun, and really thank you for working on this!

**Comment by al1brn** [comment]
Script updated
